server {
	listen 127.0.0.1:8080;
	listen 80;
	server_name example.com www.example.com;
	root /var/www/example;
	index index.html index.htm;
	client_max_body_size 10m;
	error_page 404 /errors/404.html;

	location / {
		methods GET;
		autoindex off;
	}
#qjdfhjkiqbhfhjkiqbfjkhqbfjkhbqfjkbqfjkb
	location /upload {
		methods POST;
		upload_store /var/www/uploads;
		client_max_body_size 50m;
	}

	location /php {
		cgi .php /usr/bin/php-cgi;
		index index.php;
	}

	location /old {
		return 301 /new;
	}
}