server {
	listen 8080;
	root var/www/;
	index index.html index.htm;
	client_max_body_size 10m;
	error_page 404 /errors/404.html;
	cgi .php /usr/bin/php-cgi;
	cgi .py /usr/bin/python3;

	location / {
		methods GET ;
		autoindex on;
	}
	location /upload {
		methods POST;
		upload_store /var/uploads;
		client_max_body_size 1000m;
	}

	location /php {
		cgi .php /usr/bin/php-cgi;
		index index.php;
	}

	location /python {
		methods GET POST;
		cgi .py /usr/bin/python3;
		index index.py;
	}

	location /old {
		return 301 /new;
	}
}

server {
    listen 8082;
    root fusion_web/;
	index siege.html;
	cgi .php /usr/bin/php-cgi;

	location /python {
		cgi .py /usr/bin/python3;
		index index.py;
	}
}