server {
	listen 8080;
	root var/www;
	index index.html;
	error_page 404 var/errors/404.html;
	error_page 403 var/errors/403.html;

	client_max_body_size 2000m;
	cgi .sh /bin/bash;
	cgi .py /usr/bin/python3;

	location / {
		autoindex on;
		methods POST GET;
	}

	location /uploads
	{
		root var;
		autoindex on;
	}

	location /upload {
		upload_store ./var/uploads;
		# client_max_body_size 1k;
	}

	location /return403
	{
		return 403;
	}

	location /return200message
	{
		return 200 "Hello World !";
	}
	location /return200
	{
		return 200;
	}

	location /location {
		autoindex on;
		cgi .py /usr/bin/python3;
		cgi .php /usr/bin/dfdsfdsfdsfds;
	}

	location /location/autoindex {
		autoindex on;
	}

	location /location/autoindex/test {
		autoindex on;
	}

	location /location/noautoindex {
		autoindex off;
	}

	location /location/otherlocation {
	}

	location /location/image {
	}

	location /location/old {
		return 301 /location/new/;
	}

	location /location/method {
		methods POST;
	}

	location /location/403 {
		autoindex on;
	}

	location /withindex {
	}

	location /link {
		return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
	}
	
	location /noindex {
		autoindex off;
	}
}

server {
	listen 8081;
	root var/other;
	index test.html;
}