server {
	listen 8080;
	server_name example.com;
	root var/www;
	index index.html;
	error_page 404 ./var/errors/404.html;
	error_page 500 ./var/errors/500.html;
	location /autoindex {
		autoindex on;
	}
	location /noautoindex {
		autoindex off;
	}
	location /otherlocation {
	}
	location /image {
	}
}